### ISSUE TITLE
Talk, does it work?

### ISSUE THREAD

**Issue by Morphy99** [thirtythreeforty/neolink#321]
**Is your feature request related to a problem? Please describe.**
Does the talk command work? I've tried it with my Argus pro and get the following:

```
/ # neolink talk front --config /etc/neolink.toml --input-src ~/media/doorbell.wav
[2022-11-12T20:59:29Z INFO  neolink] Neolink 0.4.0 (unknown commit) release
[2022-11-12T20:59:29Z INFO  neolink::utils] front: Connecting to camera at UID: myuuid
[2022-11-12T20:59:29Z INFO  neolink::utils] front: Logging in
[2022-11-12T20:59:29Z INFO  neolink::utils] front: Connected and logged in
thread 'main' panicked at 'internal error: entered unreachable code', src/talk/mod.rs:80:14
stack backtrace:
   0:     0x563286b597bd - std::backtrace_rs::backtrace::libunwind::trace::h4357556c585d650a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x563286b597bd - std::backtrace_rs::backtrace::trace_unsynchronized::h154a98bf0ddedacd
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563286b597bd - std::sys_common::backtrace::_print_fmt::h2979687f6ef1950e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x563286b597bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d04e59e827f4fb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x563286b7b5ac - core::fmt::write::hc90753bb4142f112
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x563286b53e11 - std::io::Write::write_fmt::ha52e2782f4a3bd92
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x563286b5af65 - std::sys_common::backtrace::_print::h036f40a453c9603b
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x563286b5af65 - std::sys_common::backtrace::print::h967f2f389d0661f9
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x563286b5af65 - std::panicking::default_hook::{{closure}}::hb0388c1054df5ebe
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x563286b5ac86 - std::panicking::default_hook::hb4a5679f0641e8af
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x563286b5b4f6 - std::panicking::rust_panic_with_hook::h55da91f28ae9c97c
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x563286b5b3a9 - std::panicking::begin_panic_handler::{{closure}}::ha6d5d75e3abde1ad
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
  12:     0x563286b59c74 - std::sys_common::backtrace::__rust_end_short_backtrace::hae84a849d394aed2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x563286b5b119 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x563286904e63 - core::panicking::panic_fmt::hf5f62850456bf94c
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x563286904d2d - core::panicking::panic::h512e7409ddadd796
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
  16:     0x563286956948 - neolink::talk::main::h7d974bad17306a09
  17:     0x5632869576ce - neolink::main::hf7a2149acc1a5c67
  18:     0x5632869316a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h954843436d70aecd
  19:     0x563286934a0d - std::rt::lang_start::{{closure}}::h2d32eb8cd0ba9e28
  20:     0x563286b4ef32 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h9b744c0fefdc9393
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280:13
  21:     0x563286b4ef32 - std::panicking::try::do_call::h59d084564bdc9764
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  22:     0x563286b4ef32 - std::panicking::try::h2fac5eedc085d56a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  23:     0x563286b4ef32 - std::panic::catch_unwind::h9421814242205f2b
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  24:     0x563286b4ef32 - std::rt::lang_start_internal::{{closure}}::h8a22d2e3a34292ac
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:48
  25:     0x563286b4ef32 - std::panicking::try::do_call::h1de2ec4bfbe13450
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  26:     0x563286b4ef32 - std::panicking::try::hcd7e19b491fbdedd
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  27:     0x563286b4ef32 - std::panic::catch_unwind::he7eb357483743dba
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  28:     0x563286b4ef32 - std::rt::lang_start_internal::h37683b205c9af4e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
  29:     0x563286957b82 - main
  30:     0x7f5b93c0da22 - <unknown>

**Comment by QuantumEntangledAndy** [comment]
Could you try it with this:

```bash
neolink talk front --config /etc/neolink.toml --file-path ~/media/doorbell.wav
```

`-input-src` just controls which microphone to use if you have multiple

**Comment by QuantumEntangledAndy** [comment]
Those messages are just informative with no errors it should have played. If not I can only assume your model has some different format. You could also try setting the debug environment variable `GST_DEBUG=3` which should print out more details about your wav conversion.

**Comment by Morphy99** [comment]
Ah ok I see what's happened. The path was incorrect, I assumed ~/ was the same as /home/. It plays now although a bit crackly like it's on vinyl :laughing:

```
neolink::talk::gst] filesrc location=/home/media/doorbell.wav ! decodebin ! audioconvert ! audioresample ! audio/x-raw,rate=16000,channels=1 ! volume volume=1.00 ! queue  ! adpcmenc blockalign=516 layout=dvi ! appsink name=thesink
0:00:00.036084399    47 0x7f329c548950 WARN                 basesrc gstbasesrc.c:3688:gst_base_src_start_complete:<filesrc0> pad not activated yet
0:00:00.046741328    47 0x7f329c633060 WARN         audio-resampler audio-resampler.c:274:convert_taps_gint16_c: can't find exact taps
```

Is there any other way to invoke this apart from ssh into the container? I want to trigger this from Home Assistant...

**Comment by QuantumEntangledAndy** [comment]
I'm not familiar with how the home assistant plugin was made. It was not us who developed it but another user. I presume you'd have to edit the home assistant plugin to add this a feature there.

**Comment by QuantumEntangledAndy** [comment]
Here's the repo for home assistant https://github.com/dm82m/hassio-addons maybe open an issue there

**Comment by QuantumEntangledAndy** [comment]
The quality is kinda low because they use an old encoding designed only for speech. It cuts out a lot of frequencies that are not in normal human speech range. I'm not sure we can do anything to help with this.

**Comment by QuantumEntangledAndy** [comment]
How are you doing the home assistant thing? I think you can overlay buttons onto the camera feed and make those run the right neolink commands but I'm not really sure how you have set it up. Usually I try and put neolink and home assistant on the same machine so no ssh required but I haven't touched ha in years now and I think they've change it a lot.

**Comment by Morphy99** [comment]
> The quality is kinda low because they use an old encoding designed only for speech. It cuts out a lot of frequencies that are not in normal human speech range. I'm not sure we can do anything to help with this.

Ah ok not to worry then.

> How are you doing the home assistant thing?

It was a case of running a shell command from HA which would ssh into the camera and then run a basic bash script. In this case I've got the added complexity of not having external shell access to the neolink container though.
